### ISSUE TITLE
code converter not found (UTF-8 to UTF-16)

### ISSUE THREAD

**Issue by Shinta** [smartinez87/exception_notification#113]
I think this issue is fixed in the version 3.0, but is happening to me right now, I love Exception Notification, can some one tell me what can i do?

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!
