### ISSUE TITLE
[Pull request] Adding an option to use exception_notification with our own notifier

### ISSUE THREAD

**Issue by gtournie** [smartinez87/exception_notification#114]
Hi,

Sorry but I didn't find a way to create a new pull request.

So, it could be great to add an option or to write a separate method (we could override) to use our own notifier. I use sidekiq and I don't want to surround all my controller's method to do that.

Thanks!

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!
