### ISSUE TITLE
MissingTemplate when using custom part ".text.erb" view

### ISSUE THREAD

**Issue by svoop** [smartinez87/exception_notification#135]
According to the README, custom parts are ".text.erb" views:

> Place your custom sections under ./app/views/exception_notifier/ with the suffix .text.erb, e.g. ./app/views/exception_notifier/_my_section1.text.erb.

However, on version 3.0.1, I get the following unless I use ".html.erb" for the partial:

    ActionView::MissingTemplate: Missing partial exception_notifier/current_user with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :slim, :arb, :coffee]}

Is the README wrong or something else?

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by svoop** [comment]
Hello! Unfortunately, I can't tell because we've switched to Airbrake/Errbit a while ago.
