### ISSUE TITLE
No email sent when ExceptionNotifier middleware configured in after_initialize block

### ISSUE THREAD

**Issue by synth** [smartinez87/exception_notification#137]
I'm scratching my head with this one:

I put in the standard lines to configure ExceptionNotifier as middleware in my production.rb file as per the readme and it works fine.  However, I need to put it in an after_initialize block such that it picks up some data configured in initializers.  When I inspect the middleware stack, ExceptionNotifier is there as expected.  When an exception is triggered, no exception email is sent.  I have inspected the logs and confirmed this.  I can send exception emails when its not in an after_initialize block.

In fact, when debugging, I've found that I add it as middleware in a before_initialize block, and it works as expected. 

Why does it not work when added into the middleware stack after the initializers are run?

ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin10.8.0]
Rails 3.2.11
exception_notification (3.0.0)

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!
