### ISSUE TITLE
An error occurred when sending a notification using 'email' notifier. NoMethodError: undefined method `underscore' for nil:NilClass

### ISSUE THREAD

**Issue by wasabia** [smartinez87/exception_notification#177]
An error occurred when sending a notification using 'email' notifier. NoMethodError: undefined method `underscore' for nil:NilClass

i have this problem

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by Mahaswami** [comment]
Just noticed this error in Rails 4.1 with JRuby 1.7.9. It seems to happen for every request
