### ISSUE TITLE
Manually sending an exception notification without having an exception

### ISSUE THREAD

**Issue by guyisra** [smartinez87/exception_notification#190]
Is it possible to send the exception notification email without having an actual exception in the code? Something I just need to trace back a certain condition, which when reached I'd like to see what brought it there using the trace and see what values the local variables have

Would it be possible? Or do I need to raise an exception (as a quick alternative) inside that condition

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!
