### ISSUE TITLE
Email dumps its contents into the log

### ISSUE THREAD

**Issue by mattrobs** [smartinez87/exception_notification#199]
When I call `ExceptionNotifier.notify_exception(e)` in my production logs I can see the entirety of the email it sends me:

![screen shot 2013-12-08 at 6 47 53 pm](https://f.cloud.github.com/assets/170421/1699959/5fd49870-5fdd-11e3-93e1-eb9e0a5b99c6.png)

Because of the backtrace, it's huge, messes up my logs and decreases signal:noise. 

Is this by design or am I doing something different?

(Context: in my Rails app, I'm doing:
````
rescue_from Exception, do |e| ExceptionNotifier.notify_exception(e) end
````
)

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!
