### ISSUE TITLE
Rails 3.2.x & ActionController::RoutingError

### ISSUE THREAD

**Issue by my-kel** [smartinez87/exception_notification#201]
Because of the ShowException middleware, this gem is not aware of ActionController::RoutingError. As we can see on the Rails 3.2 release notes (http://guides.rubyonrails.org/3_2_release_notes.html#railties), here is a solution :

"Added config.exceptions_app to set the exceptions application invoked by the ShowException middleware when an exception happens. Defaults to ActionDispatch::PublicExceptions.new(Rails.public_path)."

In my config/application.rb file I ignore no exceptions :
```ruby
config.middleware.use ExceptionNotification::Rack,
   :ignore_exceptions => [],
   ...
```

With kind regards.

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by my-kel** [comment]
Hi!

As I wrote in my previous message, I don't use this gem anymore. Now my application is running Rails 4.2.4.

So you can close this issue. Regards.
