### ISSUE TITLE
Trigger notification even when error is rescued

### ISSUE THREAD

**Issue by aug-riedinger** [smartinez87/exception_notification#208]
As I wanted to have a custom behaviour on 404 and 500 errors (= display a custom 404/500 page), I inserted these lines of code in my `application_controller.rb`.

```ruby
  if Rails.env.production?
    unless Rails.application.config.consider_all_requests_local
      rescue_from Exception, with: :render_500
      rescue_from ActionController::RoutingError, with: :render_404
      rescue_from ActionController::UnknownController, with: :render_404
      rescue_from ActionController::UnknownAction, with: :render_404
      rescue_from ActiveRecord::RecordNotFound, with: :render_404
    end
  end
```

In this case, I have the impression that the exception notification is never actually triggered, certainly because it was rescued.

How could I prevent this behaviour from happening? Or could I trigger the notification and get the stack trace into my snippet of code?

Thanks a lot, this gem is really usefull and nice!

**Comment by etipton** [comment]
Here's a pull request to handle 404s in Rails: https://github.com/smartinez87/exception_notification/pull/260

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!
