### ISSUE TITLE
Accessing both environment attributes and custom attributes for manual notifications?

### ISSUE THREAD

**Issue by hugobyrne** [smartinez87/exception_notification#238]
When manually calling an exception as per the example below the standard attributes[:env] is overwritten with the custom values [:data]. Is it possible to receive _both_ the attributes[:env] and custom values into a custom notifier?
I realise in one of the examples the request object is passed but this may not be directly available in a model. Im trying to find a solution that includes custom attributes but also passes all the env attributes  regardless of context as seems to happen with unhandled exceptions.

```
begin
  some code...
rescue => exception
  ExceptionNotifier.notify_exception(exception,
    :data => {:worker => worker.to_s, :queue => queue, :payload => payload})
end
```

**Comment by EmilioCristalli** [comment]
I think you can pass both custom data and env data when manually triggering a notification with something like this

```ruby
ExceptionNotifier.notify_exception(exception, data: { foo: "bar" }, env: request.env)
```

As you said, `request` might not be available, for example if you are calling this from a model. I'm not sure if there's a solution for this, because models don't really have access to the `request` object, because models are independent of requests (for example you can use them from rails console).

You might have to pass the `request` object to the method you are calling in the model if you really need to do this.

Unhandled exceptions are captured by a Rack middleware, as part of the request lifecycle, so they have access to the `env`
