### ISSUE TITLE
Someone used this with Rack Attack? 

### ISSUE THREAD

**Issue by bhushangahire** [smartinez87/exception_notification#396]
I am trying to use this gem to notify any blacklisting from Rack Attack gem. But it's not sending any emails. 

I am using background notification option.
`ExceptionNotifier.notify_exception(name, env: req.env, data: { message: msg })`

**Comment by Martin91** [comment]
Because rack-attack doesn't raise any exception, this gem is impossible to work.

I think you must implement one new middleware above rack-attack, and it just need to check `env['rack.attack.matched']` and `env['rack.attack.match_type']` to determine if there was any blocked or throttled requests. Additionally, you can access matched data by `env['rack.attack.match_data']` and then send it in your exception mail.

**Comment by Martin91** [comment]
@bhushangahire you might also want to insert codes in response callables https://github.com/kickstarter/rack-attack#responses

**Comment by bhushangahire** [comment]
Thanks, I have a working solution for rack-attack but not with Notification I will test above code with me solution soon.

**Comment by FLarra** [comment]
Closing this issue now. 

I'd be happy to reopen if @Martin91's example was not enough or you are still getting errors @bhushangahire.
